"""empty message

Revision ID: 2e668781fd82
Revises:
Create Date: 2025-06-28 12:33:04.616523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e668781fd82"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Currencies",
        sa.Column("ID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Code", sa.VARCHAR(length=3), nullable=False),
        sa.Column("FullName", sa.VARCHAR(length=50), nullable=False),
        sa.Column("Sign", sa.VARCHAR(length=3), nullable=False),
        sa.PrimaryKeyConstraint("ID"),
        sa.UniqueConstraint("Code"),
        sa.UniqueConstraint("FullName"),
        sa.UniqueConstraint("Sign"),
    )
    op.create_table(
        "ExchangeRates",
        sa.Column("ID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("BaseCurrencyId", sa.Integer(), nullable=False),
        sa.Column("TargetCurrencyId", sa.Integer(), nullable=False),
        sa.Column("Rate", sa.DECIMAL(precision=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["BaseCurrencyId"],
            ["Currencies.ID"],
        ),
        sa.ForeignKeyConstraint(
            ["TargetCurrencyId"],
            ["Currencies.ID"],
        ),
        sa.PrimaryKeyConstraint("ID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ExchangeRates")
    op.drop_table("Currencies")
    # ### end Alembic commands ###
