"""empty message

Revision ID: 9518fba2d753
Revises: c662d3fa972d
Create Date: 2025-07-05 13:31:15.911356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9518fba2d753'
down_revision: Union[str, Sequence[str], None] = 'c662d3fa972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExchangeRates', 'rate',
               existing_type=sa.NUMERIC(precision=6, scale=0),
               type_=sa.DECIMAL(precision=9, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExchangeRates', 'rate',
               existing_type=sa.DECIMAL(precision=9, scale=6),
               type_=sa.NUMERIC(precision=6, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
