"""Add unique constraint on currency pair

Revision ID: a4177eb1b6dc
Revises: a7a562320ea8
Create Date: 2025-07-06 13:53:01.889887

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a4177eb1b6dc"
down_revision: Union[str, Sequence[str], None] = "a7a562320ea8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_base_target_currency",
        "ExchangeRates",
        ["baseCurrencyId", "targetCurrencyId"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_base_target_currency", "ExchangeRates", type_="unique")
    # ### end Alembic commands ###
