"""Initial tables

Revision ID: c662d3fa972d
Revises:
Create Date: 2025-07-03 11:25:39.116282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c662d3fa972d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Currencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=3), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("sign", sa.VARCHAR(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("sign"),
    )
    op.create_table(
        "ExchangeRates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("baseCurrencyId", sa.Integer(), nullable=False),
        sa.Column("targetCurrencyId", sa.Integer(), nullable=False),
        sa.Column("rate", sa.DECIMAL(precision=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseCurrencyId"],
            ["Currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["targetCurrencyId"],
            ["Currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ExchangeRates")
    op.drop_table("Currencies")
    # ### end Alembic commands ###
